#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryusei Noda
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random
import string

def generater(length):
    chars = string.ascii_letters + string.digits
    password = ""
    for i in range(length):
        password += random.choice(chars)
    return password

for line in sys.stdin:
    if line == "\n":
        print("無効な入力です")
        continue
    try:
        num = int(line)
        if num <= 0:
            print("無効な入力です")
            continue
        password = generater(num)
        print("生成したパスワード: " + password)
    except:
        print("無効な入力です。")
