#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryusei Noda
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random
import string

def genereter(length):
    chars = string.ascii_letters + sting.digits
    pasword = ""
    for i in range(length):
        pasword += random.choice(chars)
    return password

for line in sys.stdin:
    if line == "\n":
        print("入力がありません")
        continue
    try:
        num = int(line)
        if num <= 0:
            print("1以上の正数を入力してください")
            continue
        password = genereter(num)
        print("生成したパスワード: " + password)
    except:
        print("無効な入力です")

